import { REAL_DATA_CONNECTED } from "@/lib/feature-flags";

export default function SimulationBanner() {
  if (REAL_DATA_CONNECTED) return null;

  return (
    <div className="border-b border-yellow-700/40 bg-yellow-900/30 text-yellow-100">
      <div className="max-w-[1600px] mx-auto px-4 py-2.5 text-sm flex items-start gap-3">
        <span className="text-yellow-300 font-bold mt-0.5">⚠</span>
        <div>
          <span className="font-semibold">Simulated data —</span>{" "}
          the FIFA price source is not yet connected. All ask prices, multiples,
          and FIRE/SELL signals shown below are generated by a formula, not
          fetched from the FIFA marketplace. Do not make selling decisions
          based on these numbers.
        </div>
      </div>
    </div>
  );
}
